---
output:
  pdf_document: 
    toc_depth: 0
    includes:
      in_header: preambulo.tex
      before_body: titulo.tex
documentclass: memoir
classoption: oneside
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
require("knitcitations")
require("bibtex")
library(rmdformats)
library(readxl)
library(dplyr)
library(plyr)
library(fOptions)
library(ggplot2)
library(kableExtra)
library(extrafont)
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)

options(tinytex.verbose = TRUE)
library(readr)
data <- read_csv("data.csv")
```

\fancyhead[LE,RO]{\slshape \rightmark}
\fancyhead[LO,RE]{\slshape \leftmark}
\lhead{CA-404 Modelos Lineales}
\rhead{\thepage}
\fancyfoot[C]{\thepage}

\tableofcontents*

\newpage
\chapter{Bitácora 1}

Se conoce a los mercados inmobiliarios como el conjunto de las acciones de oferta y demanda de bienes inmuebles, no obstante, la promoción inmobilaria, la inversión que se puede realizar por instituciones y compañias, así como individuos, y por último la financiación, la adquisión inmobilaria.

  El presente proyecto de investigación tiene como objetivo analizar con herramientas estadísticas
una base de datos cerrada y contextualizada en los Estados Unidos de América, analizar y predicir hacia donde se están movilizando los precios de las propiedades. La base de datos fue encontrada en Kaggle. Esta base toma en cuenta observaciones desde el 2 de mayo del 2014, hasta el 10 de julio del mismo año, sin embargo, la base fue publicada en el 2018. En total se encuentran 4600 observaciones.

  Sobre la base de datos, la población de estudio está determinada las casas ubicadas en ciudades de los Estados Unidos de América. La muestra de estudio es el conjunto de datos que contiene una serie de características que describen los parámetros de las casas ubicadas en las distintas ciudades de los Estados Unidos. Es decir, la muestra se refiere al comportamiento del precio de las propiedades. Ante lo anterior la unidad elemental de estudio son los datos que favorecen el precio de la propiedad inmobiliaria, observados de manera diaria por los dos meses de estudio.

  El presente compilado de datos posee algunas variables que se procede a nombrar y explicar:

\begin{itemize}
\item $date:$ La fecha en la cual se obtuvo los datos.
\item $price:$ El precio de la casa, expresado en dólares.
\item $bedrooms:$ Número de dormitorios.
\item $bathrooms:$ Número de baños
\item $sqft_living:$ Superficie habitable.
\item $sqft_lot:$ Tamaño del lote.
\item $floors:$ Número de pisos, entrepisos aceptables.
\item $waterfront:$ Vista al mar, característica dicotómica.
\item $view:$ Vista, en la escala del 0 al 4.
\item $condition:$ Condición de la casa. en la escala del 1 al 5.
\item $sqft_above:$ Superficie de la casa.
\item $sqft_basement:$ Superficie del sótano, en caso de que posean uno.
\item $yr_built:$ Año de construcción.
\item $yr_renovation:$ Año de renovación, en caso de que hubiese.
\item $street:$ Dirección 
\item $city:$ Ciudad 
\item $staetzip:$ Código postal.
\item $country:$ País.
\end{itemize}

*\textbf{Las características del área se expresan en pies cuadrados.}

  La pregúnta de la investigación sería:

 ¿Cuál es el impacto en el precio de las casas, tomando  en cuenta el número de dormitorios, el precio de la casa, número de baños, tamaño del lote, número de pisos, estado de la casa, año de construcción, superficie de la casa, año de renovación y la ciudad? 
    
  El objeto de estudio de la investigación sería buscar sentar las bases estadísticas que permitan comprender el precio de las casas
en los Estados Unidos de América, en el periodo de contrucción de ellas, desde 1900 hasta el 2014.

  Algunos conceptos básicos que delimiten teóricamente la pregunta de investigación serían:

\begin{itemize}
\item Casa: El término significa la construcción de una o pocas plantas que están destinadas a habitarlas familias, caso opuesto con respecto a los edificios de múltiples departamentos o pisos, según la definición de la RAE (2022).

\item Precio de vivienda: Según Rafael Bueno (2021) el precio de una vivienda, el cual no es solo tarifa, si no, que es parte de varios componentes de distintos rango, según el momento del mercado. 
Superficie construida: Según la revista AD (2018), se le llama de esa forma, a la suma total de los metros cuadrados que están dentrp del perímetro de la casa.

\item Estado físico de vivienda: Según el INEC (2013), se define estado físico de la vivienda al estado de los componentes de la casa, como paredes, techo y el piso.

\item Dimensión del terreno: Según Echazarreta (2018), el tamaño estánda de este es de 60 y los 84 metros cuadrados de terreno.

\item Valoración de propiedad: Según la ConsultoriayPeritaciones C\&P (2019) la valoración de bienes muebles o inmuebles es un proceso requerido en diversidad de ámbitos administrativos, empresariales, judiciales, etc.

\item Plusvalía: Karl Marx (1818-1883) lo define como la diferencia entre el valor de uso y el valor de cambio, que resulta en un beneficio para el capitalista y es el motor del capitalismo.

\item Depreciación: La depreciación es la pérdida de valor de un bien como consecuencia de su desgaste con el paso del tiempo. (Vázquez, 2016)
\end{itemize}

\printbibliography
