---
title: "Capitulo16"
author: "Maria Jose Corea"
date: "2022-11-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Ejercicio 16.9

```{r cars}
F<-function(t){
  F<-(t*(t+1))/20
}

probs<-diff(F(0:4))
Esperada<-probs*150#es la suma de todas las observaciones
obs<-c(21,27,39,63)

chicuadrado<-sum((Esperada-obs)^2/Esperada)

pchisq(q=chicuadrado,df=3,lower.tail = FALSE)
qchisq(0.95,df=3)#valor crítico
```
## Ejercicio 16.17
Poisson

```{r}
pchisq(q=0.14,df=2,lower.tail = FALSE)
qchisq(0.95,df=2)#valor crítico
```
Geométrica

```{r}
pchisq(q=23.77,df=2,lower.tail = FALSE)
qchisq(0.95,df=2)#valor crítico
```
Binomial Negativa
```{r}

```
Binomial 

```{r}
qchisq(0.95,df=1)#valor crítico
```

16.23

```{r}
library(fitdistrplus)
library(actuar)
x<- c(27, 82, 115, 126, 155, 161, 243, 294, 340, 384, 457, 680, 855, 877, 974, 1193, 1340, 1884, 2.558, 3.476 )

fit_weibull<- fitdist(data =x, distr="weibull",method="mle")
cdfcomp(fit_weibull)
denscomp(fit_weibull)
plot(fit_weibull)
```

```{r}

fit_Exponencial<- fitdist(data =x,distr="exp",method="mle", start = list(rate= 1/mean(x)), lower=0, upper=1)

lambda=1/mean(x)

y<-dexp(x,rate=lambda)
hist(x,probability=T)
lines(y~x,col="red")
mledist(data=x,distr = "exp",start = list(rate=9))
```
Distribución transformada

```{r}

```

