---
output:
  pdf_document: 
    toc_depth: 0
    includes:
      in_header: preambulo.tex
      before_body: titulo.tex
documentclass: memoir
classoption: oneside
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
require("knitcitations")
require("bibtex")
library(rmdformats)
library(readxl)
library(dplyr)
library(plyr)
library(fOptions)
library(ggplot2)
library(kableExtra)
library(extrafont)
library(scales)
options(max.print="75")
opts_chunk$set(echo=FALSE, 
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)

```

\fancyhead[LE,RO]{\slshape \rightmark}
\fancyhead[LO,RE]{\slshape \leftmark}
\lhead{CA-409 Distribución de Pérdidas}
\rhead{Bitácora \thechapter}
\fancyfoot[C]{\thepage}

\tableofcontents*

\newpage
\chapter{Bitácora I}


\section{Sobre la base de datos}

```{r}
base <- read.csv('~/GitHub/II-2022/Distribución de pérdidas/Fire Incidents Data.csv')

perd <- base$Estimated_Dollar_Loss
#Los elementos de la base donde no se cuantificaron perdidas no interesan
base <- base[!is.na(perd),]
perd <- perd[!is.na(perd)]


```


```{r}
p <- read.csv('~/GitHub/II-2022/Distribución de pérdidas/columnas.txt',sep = ',', fileEncoding = "UTF-8")

knitr::kable(p, caption = "Descripción completa de la base", longtable = TRUE) %>%
  column_spec(2, width = "7cm") %>% footnote(general = 'Fuente: Elaboración propia', general_title = '') %>%
  kable_styling(latex_options = c("repeat_header"),
                repeat_header_continued = "Continua en siguiente pag",
                repeat_header_text = "\\textit{(Continuación)}"
                )

```

\chapter{Bitácora II}

\section{Graficos}

```{r}
out <- quantile(perd, 0.95) #cuantil del 95 por ciento

grafico1 <-
  ggplot(base, aes(x = log(Estimated_Dollar_Loss))) + 
  geom_histogram(color =
                   "darkblue", fill = "lightblue") + theme_bw() +
  labs(
    y = "Frecuencia",
    x = "Pérdida en escala logarítmica",
    title = "Gráfico 1: Histograma en escala logarítmica de las pérdidas",
    caption = "Fuente: Elaboración propia"
  )

grafico1

base$Extremo <- perd >= out

grafico2 <-
  ggplot(data = base) + geom_bar(
    mapping = aes(x = Extremo),
    color = c('blue', 'red'),
    fill = c('lightblue', 'pink'),
    width = 0.5,
    na.rm = TRUE
  ) + theme_bw() +
  labs(
    y = "Frecuencia",
    x = "Cuantil",
    title = "Gráfico 1: Frecuencia del estimado de pérdidas de acuerdo al cuantil 0.95",
    caption = "Fuente: Elaboración propia"
  ) +
  scale_x_discrete(labels = c("Menor 95%", "Mayor o igual 95%"))
grafico2


df <-
  data.frame(
    Name = c("Masa cuantil menor a .95", "Masa cuantil mayor o igual a .95"),
    Amount = c(sum(perd[perd < out]), sum(perd[perd >= out]))
  )

grafico3 <- ggplot(df, aes(x = Name, y = Amount)) + geom_bar(
  stat = "identity",
  color = c('blue', 'red'),
  fill = c('lightblue', 'pink'),
  width = 0.5,
  na.rm = TRUE
) + theme_bw() +
  labs(
    y = "Masa de la pérdida",
    x = "Cuantil",
    title = "Gráfico 3: Masa del estimado de pérdidas de acuerdo al cuantil 0.95",
    caption = "Fuente: Elaboración propia"
  ) + scale_y_continuous(labels = comma) + scale_x_discrete(limits = df$Name)
grafico3

```







\printbibliography
